version: '3.7'

services:
    mysql:
        image: arm64v8/mysql:8.4.2
        container_name: my_mysql
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mysql_data:
