version: '3.9'

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: always
    shm_size: 128mb  # set shared memory limit
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: 'virtual_file_system'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
