DROP TABLE IF EXISTS employment;
DROP TABLE IF EXISTS education;
DROP TABLE IF EXISTS friendship;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS institutions;
DROP TABLE IF EXISTS degree;
DROP TABLE IF EXISTS companies;
